### PR TITLE
added wsavran as maintainer

### PR DESCRIPTION
**Pull request by wsavran**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wsavran** [comment]
@conda-forge/core i goofed and overwrote myself as a maintainer with a github account. can you merge this pr to add myself back to the maintainers list? thank you!

**Comment by ocefpaf** [comment]
> @conda-forge/core i goofed and overwrote myself as a maintainer with a github account. can you merge this pr to add myself back to the maintainers list? thank you!

I'm not sure I follow. Did you change your GH handle recently? Looks like @billtr0n still exists. Did you lost access to that account?

**Comment by wsavran** [comment]
yes, @billtr0n is my old handle, but its registered to an .edu email that has been discontinued.

**Comment by ocefpaf** [comment]
> yes, @billtr0n is my old handle, but its registered to an .edu email that has been discontinued.

Can you remove it then? For safety reasons it is better to remove handles that are not active.

**Pull request merged**
